# -*- coding: utf-8 -*-
"""AirTrack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHam5GOVojEQAfoKZgQPtoWs19AHMJ-V
"""

import requests

LAT = 45.07
LON = 7.69
RADIUS_NM = 150  # max 250 nm

url = f"https://api.airplanes.live/v2/point/{LAT}/{LON}/{RADIUS_NM}"
r = requests.get(url, timeout=30)
print("Status:", r.status_code)
r.raise_for_status()

data = r.json()
type(data), list(data.keys())[:10]

import pandas as pd
from datetime import datetime, timezone

aircraft = data.get("ac", [])
print("Aircraft records:", len(aircraft))

df = pd.DataFrame(aircraft)
df["snapshot_time_utc"] = datetime.now(timezone.utc).isoformat()

df.head()

out = "airplanes_live_snapshot.csv"
df.to_csv(out, index=False)
print("Saved:", out)

import time

snapshots = []
N = 60          # 60 snapshots
SLEEP = 1.1     # >1 sec to respect the limit

for i in range(N):
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    payload = r.json()

    dfi = pd.DataFrame(payload.get("ac", []))
    dfi["snapshot_time_utc"] = datetime.now(timezone.utc).isoformat()
    snapshots.append(dfi)

    print(f"{i+1}/{N}: rows={len(dfi)}")
    time.sleep(SLEEP)

df_all = pd.concat(snapshots, ignore_index=True)
df_all.to_csv("airplanes_live_timeseries.csv", index=False)
print("Saved: airplanes_live_timeseries.csv rows=", len(df_all))

from google.colab import files
files.download("airplanes_live_snapshot.csv")

import pandas as pd
import numpy as np
import pandas as pd

df = df.copy()
print(df.shape)

df["snapshot_time_utc"] = pd.to_datetime(df["snapshot_time_utc"], utc=True, errors="coerce")

# Normalize common string fields
for c in ["hex", "type", "flight", "r", "t", "desc", "category", "squawk", "emergency"]:
    if c in df.columns:
        df[c] = df[c].astype("string")

if "flight" in df.columns:
    df["flight"] = df["flight"].str.strip()

# Columns that should be numeric
num_cols = [
    "alt_baro","alt_geom","gs","ias","tas","mach","wd","ws","oat","tat",
    "track","track_rate","roll","mag_heading","true_heading",
    "baro_rate","geom_rate","nav_qnh","nav_altitude_mcp","nav_heading",
    "lat","lon","nic","rc","seen_pos","version","nic_baro","nac_p","nac_v",
    "sil","gva","sda","alert","spi","mlat","tisb","messages","seen","rssi",
    "dst","dir","nav_altitude_fms","dbFlags","ownOp","year"
]
for c in num_cols:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")

# Wrap angles to [0, 360)
for c in ["track","mag_heading","true_heading","wd","dir","nav_heading"]:
    if c in df.columns:
        df[c] = df[c] % 360

df.shape

def pct(x):
    return round(100 * x, 2)

summary = {}
summary["rows"] = len(df)
summary["unique_hex"] = df["hex"].nunique(dropna=True) if "hex" in df.columns else None
summary["unique_flights"] = df["flight"].nunique(dropna=True) if "flight" in df.columns else None
summary["time_min"] = df["snapshot_time_utc"].min()
summary["time_max"] = df["snapshot_time_utc"].max()

# Emergency flags / squawk presence
if "emergency" in df.columns:
    summary["emergency_nonempty"] = int(df["emergency"].fillna("").str.len().gt(0).sum())
if "squawk" in df.columns:
    summary["squawk_nonnull"] = int(df["squawk"].notna().sum())

summary

missing = (df.isna().mean().sort_values(ascending=False) * 100).round(1)
missing.head(25)

import matplotlib.pyplot as plt

def hist(col, title, bins=60):
    if col not in df.columns:
        print(f"Missing column: {col}")
        return
    s = df[col].dropna()
    if s.empty:
        print(f"No data for: {col}")
        return
    plt.figure()
    plt.hist(s, bins=bins)
    plt.title(title)
    plt.xlabel(col)
    plt.ylabel("count")
    plt.show()

hist("alt_baro", "Barometric altitude (likely feet)")
hist("gs", "Ground speed (likely knots)")
hist("tas", "True airspeed (likely knots)")
hist("baro_rate", "Baro vertical rate (likely ft/min)")

import matplotlib.pyplot as plt

if {"lat","lon"}.issubset(df.columns):
    d = df[["lat","lon"]].dropna()
    plt.figure()
    plt.scatter(d["lon"], d["lat"], s=6)
    plt.title("Aircraft positions (lon/lat)")
    plt.xlabel("Longitude")
    plt.ylabel("Latitude")
    plt.show()
else:
    print("lat/lon not available")

if "dst" in df.columns:
    print("dst (distance) summary:")
    display(df["dst"].describe())

    plt.figure()
    plt.hist(df["dst"].dropna(), bins=60)
    plt.title("Distance from center (dst)")
    plt.xlabel("dst")
    plt.ylabel("count")
    plt.show()

if "dir" in df.columns:
    plt.figure()
    plt.hist(df["dir"].dropna(), bins=36)
    plt.title("Direction/bearing from center (dir)")
    plt.xlabel("dir (degrees)")
    plt.ylabel("count")
    plt.show()

def classify_phase(vr_fpm):
    if pd.isna(vr_fpm):
        return "unknown"
    if vr_fpm > 300:
        return "climb"
    if vr_fpm < -300:
        return "descent"
    return "level"

df["phase"] = df["baro_rate"].apply(classify_phase) if "baro_rate" in df.columns else "unknown"
df["phase"].value_counts(dropna=False)

import numpy as np

needed = {"wd","ws","track"}
if needed.issubset(df.columns):
    # Convert degrees to radians
    trk = np.deg2rad(df["track"])
    wd = np.deg2rad(df["wd"])  # wind direction (usually "from", meteorological convention)

    ws = df["ws"]

    # If wd is "from", the wind vector points opposite direction of wd.
    # Headwind positive when opposing motion along track.
    # We'll compute components along the aircraft track axis.
    wind_to = wd + np.pi  # direction wind is going TO

    headwind = ws * np.cos(wind_to - trk)       # + = tailwind, - = headwind (by this sign convention)
    crosswind = ws * np.sin(wind_to - trk)      # signed crosswind

    df["tailwind_kn"] = headwind
    df["crosswind_kn"] = crosswind

    display(df[["ws","wd","track","tailwind_kn","crosswind_kn"]].dropna().head(10))

    plt.figure()
    plt.hist(df["tailwind_kn"].dropna(), bins=60)
    plt.title("Tailwind component (kn)  (negative = headwind)")
    plt.xlabel("tailwind_kn")
    plt.ylabel("count")
    plt.show()
else:
    print("Need wd, ws, track columns for wind components.")

if {"gs","tas"}.issubset(df.columns):
    d = df[["gs","tas"]].dropna()
    plt.figure()
    plt.scatter(d["tas"], d["gs"], s=8)
    plt.title("Ground speed vs True airspeed")
    plt.xlabel("tas")
    plt.ylabel("gs")
    plt.show()

    df["gs_minus_tas"] = df["gs"] - df["tas"]
    display(df["gs_minus_tas"].describe())
else:
    print("Need gs and tas.")

if "hex" in df.columns:
    display(df["hex"].value_counts().head(15).to_frame("rows"))

if "messages" in df.columns:
    display(df[["hex","flight","messages"]].dropna().sort_values("messages", ascending=False).head(15))

if "seen" in df.columns:
    display(df[["hex","flight","seen"]].dropna().sort_values("seen").head(15))  # smaller = seen more recently in many feeds